# Header Menu
menu:
  Home: /
  #Projects: /projects/
  Blog: /archives/ # can set archive-dir in root config to custom value
  Contact: /contact/
  About: /about/
   
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname: 
google_analytics:
swiftype_install_key: 

# Social
social:
  github: https://github.com/armixy
  twitter: https://twitter.com/ptsteadman
  facebook: https://www.facebook.com/ptsteadman
  rss: atom.xml
  linkedin: https://linkedin.com/in/ptsteadman
  stackoverflow: http://stackoverflow.com/users/2480493/patrick-steadman

# Miscellaneous
color_scheme: blue   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
twitter_widget_id: "678830341331820544" # as a string, from https://twitter.com/settings/widgets
twitter_username: computerlab_ # twitter username without the @
default_author: Kyle Chin

about: Change myself, change the world.
phone: +1 (725)300-6586
email: qin_jin@live.com
address_1: Tropicana Gardens, 6585 El Colegio Rd,
address_2: Isla Vista, Goleta,
address_3: Santa Barbara, CA 11249
skype: Kyle Chin
lat: 34.4167655289
long: -119.8579511046

highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
